[package]
name = "font2sdf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
easy-signed-distance-field = { version = "0.1.1", features = ["render", "export", "font"] }
