[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
glam = "0.28.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["extra-traits", "full"] }

[dev-dependencies]
indoc = "2.0.5"
